set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property PACKAGE_PIN H14 [get_ports {key[0]}]
set_property PACKAGE_PIN F14 [get_ports {key[1]}]
set_property PACKAGE_PIN H13 [get_ports {key[2]}]
set_property PACKAGE_PIN M13 [get_ports {key[3]}]
set_property PACKAGE_PIN G14 [get_ports {key[4]}]
set_property PACKAGE_PIN L13 [get_ports {led[0]}]
set_property PACKAGE_PIN F13 [get_ports {led[1]}]
set_property PACKAGE_PIN J14 [get_ports {led[2]}]
set_property PACKAGE_PIN L14 [get_ports {led[3]}]
set_property PACKAGE_PIN J13 [get_ports {led[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN M10 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN H11 [get_ports clk]
